### ISSUE TITLE
FIR filter design functions

### ISSUE THREAD

**Issue by jfsantos** [JuliaDSP/DSP.jl#10]
Add FIR filter design functions (window method, Remez exchange algorithm). These functions could be ported from Scipy.

**Comment by JayKickliter** [comment]
It pays to ask: Liquid DSP is [going to transition](https://github.com/jgaeddert/liquid-dsp/issues/6) to MIT license.

**Comment by JayKickliter** [comment]
It pays to ask: Liquid DSP is [going to transition](https://github.com/jgaeddert/liquid-dsp/issues/6) to MIT license.

**Comment by jfsantos** [comment]
We already have the FIR design functions that came from Multirate.jl, and @JayKickliter has a proposal for a firls implementation in other issue. I think we can close this issue for now.
