### ISSUE TITLE
Cannot convert FIRWindow digital filters to PolynomialRatio coefficient types

### ISSUE THREAD

**Issue by galenlynch** [JuliaDSP/DSP.jl#115]
While trying to get `filtfilt` to work for me, I tried to convert my FIR filter into a PolynomialRatio type, but was unable to do so. I was following an example in the documentation to do this:

```
julia> order = 81
response = Highpass(300; fs = 30000)
design = FIRWindow(hamming(order))
hp_300 = digitalfilter(response, design)
tf = convert(PolynomialRatio, hp_300)
ERROR: MethodError: `convert` has no method matching convert(::Type{DSP.Filters.PolynomialRatio{T<:Number}}, ::Array{Float64,1})
This may have arisen from a call to the constructor DSP.Filters.PolynomialRatio{T<:Number}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  DSP.Filters.PolynomialRatio{T<:Number,S<:Number}(::Union{Array{T<:Number,1},T<:Number}, ::Union{S<:Number,Array{S<:Number,1}})
  call{T}(::Type{T}, ::Any)
  convert{Z,P,K}(::Type{DSP.Filters.PolynomialRatio{T<:Number}}, ::DSP.Filters.ZeroPoleGain{Z,P,K})
```

**Comment by simonster** [comment]
We probably need to start wrapping FIR filter coefficients in their own type. At the moment they are just ordinary vectors of taps, which is convenient for some purposes, but for this purpose it seems to ambiguous.

**Comment by galenlynch** [comment]
The main reason I was trying to do this is because the documentation for `filtfilt` suggested that I needed some sort of coefficient type, which was reinforced by the methods available for `filtfilt`. #114 addresses the reason I was trying to do this in the first place, but I'm not sure if wrapping the taps in a coefficient type would have other benefits.

**Comment by simonster** [comment]
While it shouldn't generally be necessary to convert FIR taps to other representations, I think it still ought to work. Unfortunately our current APIs are a little too IIR-centric because it was what was implemented first.
