### ISSUE TITLE
Inline documentation using Julia 0.4 new doc system

### ISSUE THREAD

**Issue by jfsantos** [JuliaDSP/DSP.jl#116]
Julia 0.4 has a [new documentation system](https://github.com/JuliaLang/julia/pull/8791) which allows adding inline docs that can be accessed via the REPL. We should make sure all the functions exported by the DSP.jl module have inline docs. They do not need the same level of detail as our online docs, but should at least be slightly useful.

**Comment by simonster** [comment]
Yes, this is a good idea. Ideally we'd be able to use the same docs for inline help and the website, but AFAIK there's no general way to do that yet. @shashi has a script [here](https://gist.github.com/shashi/5b2c8cd95d2f3834f9c7), but it doesn't support sections like our current sphinx/rst docs. We could also try to adapt [genstdlib.jl](https://github.com/JuliaLang/julia/blob/master/doc/genstdlib.jl) from Base, although that's clearly a bit of a hack.

**Comment by jfsantos** [comment]
Do you think we should maybe port our current docs to inline docs by hand and then figure out a way of extracting it to rst/md? I could start working on that in a separate branch.

I've seen some people argue that the online docs should be an expanded version of the inline docs, but I don't have a strong opinion on it. I'm inclined to agree in cases where the documentation for each function is huge, includes several references and such, but ours is pretty succinct and should work well for both formats.
