### ISSUE TITLE
welch_pgram problem

### ISSUE THREAD

**Issue by wherrera10** [JuliaDSP/DSP.jl#117]
When passing some audio data as a normalized Float64 array, the following occurs with a call to welch_pgram:

fchunk is Array{Float64,1} of size (16384,)

call:
pxx, freqs = welch_pgram(fchunk, fs=44100)

ERROR: LoadError: MethodError: `start` has no method matching start(::DSP.Periodograms.Periodogram{Float64,DSP.Util.Frequencies}) while loading ...

**Comment by simonster** [comment]
`welch_pgram` returns a periodogram object, not a tuple. To get the power and frequencies, you'd want:

```julia
pg = welch_pgram(fchunk, fs=44100)
pxx = power(pg)
freqs = freq(pg)
```

Is there a place where the docs are wrong?

**Comment by wherrera10** [comment]
Thanks.  It looks like the freq field is an object as well. I had to map it to a float array to get it to behave the way I needed.

Thanks for the quick reply.
