### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by iceblue25** [JuliaDSP/DSP.jl#119]
I m trying to call the spectrogram function and I get the following segfault on ver 0.4.2

unknown function (ip: (nil))
jlcall_call_21463 at  (unknown line)
jl_apply_generic at lib/julia/libjulia.so (unknown line)
plan_rfft at fft/FFTW.jl:643
plan_rfft at fft/FFTW.jl:665

**Comment by jfsantos** [comment]
How did you install Julia? This error is happening on an internal Julia call, not on DSP.jl. Our tests are passing on both 0.4 and 0.5, so I don't think they changed anything in the FFT API that we didn't cover.

**Comment by iceblue25** [comment]
I downloaded the generic 64bit linux tar . I m not sure why it doesnt work since it used work.

**Comment by jfsantos** [comment]
Can you send us a minimal reproducible example?
