### ISSUE TITLE
ControlSystems + DSP

### ISSUE THREAD

**Issue by ma-laforge** [JuliaDSP/DSP.jl#145]
Copying https://github.com/JuliaControl/ControlSystems.jl/issues/92:

There seems to be alot of overlap in the facilities provided by the https://github.com/JuliaDSP and https://github.com/JuliaControl groups.

| JuliaControl | JuliaDSP |
| - | - |
| `zpk` | `ZeroPoleGain` |
| `tf` / `SisoRational` | `PolynomialRatio` |
| ... | ... |

 - It appears that ControlSystems is targeting a "Traditional math API", whereas the DSP module is going for Julian function names.
 - ControlSystems has methods to generate bode plots of `LTISystems` - a facilty that the JuliaDSP users might also want to apply to their solutions.

I think both solutions have merit - and I am not asking anybody to necessarily comply with the other group's solutions (that might actually hinder development).  However: I am could not tell if either one of the groups was aware of the other.

Eventually, (if the two solutions need to go in their own seperate direction) it might be nice to at least have a bridging package so that users can easily convert data structures and use the other module's facilities - almost transparently.

**Comment by ViralBShah** [comment]
I am closing this since it feels more appropriate for a discussion on discourse. Please reopen if folks prefer to discuss/engage here. It also seems that the discussion happened on the Controls side (in the linked issue).
