### ISSUE TITLE
MTaper

### ISSUE THREAD

**Issue by aeroflux** [JuliaDSP/DSP.jl#150]
So I have been trying to use the MT_pgram and stumbled upon a problem:

> ERROR: OutOfMemoryError()
 in stegr!(::Char, ::Char, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64, ::
Float64, ::Int64, ::Int64) at .\linalg\lapack.jl:3684
 in eigfact!(::SymTridiagonal{Float64}, ::UnitRange{Int64}) at .\linalg\tridiag.
jl:139
 in dpss(::Int64, ::Int64, ::Int64) at C:\Users\\.julia\v0.5\DSP\src\windo
ws.jl:130

Not sure what to make of it and I noticed that iceil is still listed in the documentation where I believe it should be just ceil.

**Comment by aeroflux** [comment]
Right, as far as I can tell there is a limit to the amount of samples that can be processed, which is around ~50000.

**Comment by simonster** [comment]
It looks like there is a bug in Julia's LAPACK bindings where it tries to allocate enough memory for all of the eigenvectors of a symmetric tridiagonal matrix even if only a few are needed. It's an easy fix (https://github.com/JuliaLang/julia/pull/20459), but it may be a while before it ends up in a release version of Julia.

**Comment by aeroflux** [comment]
Thanks, really appreciate the help! I will keep a look out for the merge. Should I close the issue now or when the merge has been completed and the routine tested?
