### ISSUE TITLE
remove FFTW dependency for 0.6 tags?

### ISSUE THREAD

**Issue by ssfrr** [JuliaDSP/DSP.jl#176]
running `using DSP` on 0.6 currently gives:

```
INFO: Precompiling module DSP.
WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/home/sfr/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to DSP:    
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/home/sfr/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **
```

It looks like in [this PR](JuliaStats/Distributions.jl#637) of Distributions.js they had the same issue and ended up releasing a 0.6-tagged package without FFTW. I'm not 100% sure what the FFTW situation is, but currently something is amiss.

@ararslan (sorry)

**Comment by ararslan** [comment]
What version of DSP do you have?

**Comment by ssfrr** [comment]
* DSP v0.3.3
 * FFTW v0.0.4

That's what I get after a Pkg.update()

**Comment by ararslan** [comment]
*sigh* Okay. It's diagnosing time. Thanks for the report.
