### ISSUE TITLE
deconv(b,a) modifies b 

### ISSUE THREAD

**Issue by hessammehr** [JuliaDSP/DSP.jl#188]
On Julia 0.6.1 (`Base.deconv`) and nightly (`DSP.conv`):

```julia
a = [1.0, 2.0, 3.0]
c = deconv(a, [1000.0, 0.0])
a
```
gives
```
3-element Array{Float64,1}:
 0.001
 0.002
 0.003
```
My understanding is this function is not supposed to modify its arguments.

**Comment by hessammehr** [comment]
The culprit seems to be `dspbase.jl:53`
```julia
if a[1] != 1
    norml = a[1]
    a ./= norml
    b ./= norml
end
```

**Comment by martinholters** [comment]
Yes, that `./=` should probably just be a `/=`. Do you want to open a PR with that change?
