### ISSUE TITLE
Misplaced parens in gaussian window definition

### ISSUE THREAD

**Issue by ssfrr** [JuliaDSP/DSP.jl#204]
The current [gaussian window](https://github.com/JuliaDSP/DSP.jl/blob/b358239fdbaeb9061a0337964b652d7ddced61a8/src/windows.jl#L131-L136) seems similar to the [wikipedia description](https://en.wikipedia.org/wiki/Window_function#Gaussian_window) except that the grouping in the denominator is wrong (`n-1/2` vs `(n-1)/2`).

There's no reference in the docs for what is intended, but this doesn't seem right.

Also if you add the parens to get:
```julia
[exp(-0.5*((k-(n-1)/2)/(sigma*(n-1)/2))^2) for k=0:(n-1)]
```

You get the same answer as
```julia
g(x) = exp(-0.5*(x/sigma)^2)
g.(linspace(-1.0, 1.0, n)
```

Which seems like a pretty reasonable definition (defining `sigma` as the std. dev as a fraction of the total window length, so `sigma=0.5` corresponds to the right and left edges of the window being 1 stddev away).

The other issue with the current implementation is that it breaks the principle that the discrete windows are just sampled versions of the underlying continuous function (`triang` also has this property, but I think that's expected). With the current implementation the shape of the window changes slightly as you vary `n`.

If this is a bug and we want to fix it, deprecation is a bit of a challenge. Perhaps during the deprecation period we define the function:

```julia
function gaussian(n, sigma; legacy=true)
    legacy && depwarn(
        """
        As of DSP v0.5.0 `sigma` is interpreted as the std dev as a fraction of the window
        length. use `gaussian(n, sigma; legacy=false)` to opt into the new definition
        during the deprecation period. After the deprecation period this will be the default.
        """, :legacy_gaussian)
    if legacy
        # old definition...
    else
        # new definition
end
```

I do worry a little about this deprecation strategy, because after the deprecation window is over any old code that didn't get updated will be silently broken. I'm not sure if there's a sensible interpretation for the current meaning of `sigma`, but I wouldn't be surprised if there's code out there that just eyeballed a reasonable value for it, and those windows will be messed up.

On the other hand, the package is not yet at 1.0, and it would be nice to have a `sigma` value that meant something.

I can do the PR, I just wanted to get some feedback on this strategy.

**Comment by martinholters** [comment]
I agree the current definition looks fishy. A less breaking change would be to change `n-1/2` to `n-1`. Then the window would correspond to `g.(linspace(-0.5, 0.5, n)` which is also not completely unreasonable (note the total length of 1.0). We might call that a mere bugfix and go without a deprecation; for largish `n`, the difference will probably be insignificant. Also, the upper limit of 0.5 on sigma suggests that @kofron had this definition in mind. (Though I don't understand the need for an upper limit anyway.)

However, I could (by a very brief glance) not find a reference using that definition. On the contrary, Matlab uses the same definition as given on Wikipedia. Worth looking around for more prior art before making a decision? A justification for not making a breaking change would be nice :smile:

**Comment by ssfrr** [comment]
Well, [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.windows.gaussian.html#scipy.signal.windows.gaussian) doesn't scale the `std` argument at all, so you end up doing something like `gaussian(128, 20)`  

Matlab seems to use the wikipedia definition but uses the `alpha=1/sigma` as the parameter.

Given that there doesn't seem to be a strong prior art, I like your suggestion of just dropping the `/2`. So the docstring should be something like

```julia
doc"""
    gaussian(n, sigma)

Gives an n-sample gaussian window defined by $w(x) = e^{ -\frac 1  2 \left(\frac x  \sigma \right)^2 }$
in the range $[-0.5, 0.5]$
"""
```

BTW I also don't understand the restriction to `0.5` or below. It doesn't seem like there's anything magical about that number. I'd be happy to drop that.

**Comment by ssfrr** [comment]
Yeah, that sounds good. I'll PR in the next couple days.
