### ISSUE TITLE
filtfilt with complex vector on julia-1.0 fails with MethodError

### ISSUE THREAD

**Issue by berndblasius** [JuliaDSP/DSP.jl#222]
Attempting to filter a complex-valued array with DSP on julia 1.0 produces a MethodError.

Here a constructed code example:
```n=500
 x = rand(n) + im*rand(n)  
 b = ones(n) / n
 filtfilt(b,x)
```

Running this on julia-1.0 (with DSP version v0.5.1) leads to
ERROR: MethodError: no method matching _fftfilt!(::Array{Complex{Float64},2}, ::Array{Float64,1}, ::Array{Complex{Float64},2}, ::Int64)
Closest candidates are:
  _fftfilt!(::AbstractArray{T<:Real,N} where N, ::AbstractArray{T<:Real,1}, ::AbstractArray{T<:Real,N} where N, ::Integer) where T<:Real at /home/bernd/.julia/packages/DSP/Cq0iO/src/Filters/filt.jl:549

The same code works without problems in julia-0.6 (with DSP version 0.4.0).
There are no arrow messages when the length of x or of b is much smaller.

The same code works for real valued arrays, i.e. Array{Float64,1}. So it's no deal-breaker because I still can filter real and imaginary parts independently.

**Comment by rob-luke** [comment]
I ran your code (with n = 100) on Julia v0.7 and it worked. But can confirm the error on Julia 1.0 with a fresh install.

**Comment by berndblasius** [comment]
Sorry, I forgot to give the value of n which gives problems. In my case I used n=500. 

Running the same code as yours will n = 500 produces the error on my machine.

As I wrote, for small values of n there are no errors. Strangely enough, the threshold seems to be n=296. That is, the error appears when n>=297.

**Comment by rob-luke** [comment]
Ok I see the same error as @berndblasius on Julia 1.0 when I run 

```julia
using DSP
n = 297   # or anything higher
x = rand(n) + im*rand(n)  
b = ones(n) / n
a = filtfilt(b,x)
```

**Comment by galenlynch** [comment]
This seems to work now.
