### ISSUE TITLE
Error using Util.hilbert() [Fedora 28]

### ISSUE THREAD

**Issue by koenigjaeger** [JuliaDSP/DSP.jl#227]
OS: Fedora 28
CPU: Intel® Core™ i7 CPU 860 @ 2.80GHz × 8 / AMD Ryzen5 1600
GPU: AMD® Cape verde / AMD RX580
Julia: 0.6.3 (2018-05-28 20:20 UTC) x86_64-redhat-linux

I was trying to use the hilbert transform on two different computers and I was getting the following error:

`ERROR: error compiling Type: error compiling _init_: could not load library "libfftw3f_threads"
libfftw3f_threads.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] #plan_rfft#17(::UInt32, ::Float64, ::Function, ::Array{Float64,1}, ::UnitRange{Int64}) at ./fft/FFTW.jl:649
 [2] #plan_rfft#19(::Array{Any,1}, ::Function, ::Array{Float64,1}) at ./fft/FFTW.jl:671
 [3] hilbert(::Array{Float64,1}) at /home/apattyn/.julia/v0.6/DSP/src/util.jl:36
 [4] macro expansion at ./REPL.jl:97 [inlined]
 [5] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
`

I tried to just test it using...
`sig = 2*sin(0:1/100:2*pi)-1;
tfm = Util.hilbert(sig);
`

As well as with real radio frequency data, with the following code...
`sensor_data_hil = abs.(Util.hilbert.(sensor_data_cropped))`

I tried deleting the .julia file and re-downloading and building with nothing helping. It is however working on an XPS 13 with following specs...
CPU: Intel i5-5200U
GPU: Intel HD 5500
Julia: 0.6.3 (2018-05-28 20:20 UTC) x86_64-redhat-linux

**Comment by rickhg12hs** [comment]
What happens when you try `fft(rand(10))`?

**Comment by koenigjaeger** [comment]
The same error occurs.

-------- Original Message --------

**Comment by rickhg12hs** [comment]
How did you install Julia?  Something is wrong here.

**Comment by koenigjaeger** [comment]
Through Fedora's provided packages. I mean it looks like it can't load libfftw3f_threads, and from what I've seen so far this only has occurred on computers with AMD GPUs. My laptop that has Intel integrated graphics and seems to be fine.

**Comment by koenigjaeger** [comment]
Alright so I looked for something like libfftw3f_threads in the Fedora repos and found fftw.

`[$USER@$HOST ~]$ dnf info fftw
Last metadata expiration check: 0:02:15 ago on Sat 08 Sep 2018 02:05:25 PM EDT.
Installed Packages
Name         : fftw
Version      : 3.3.5
Release      : 11.fc28
Arch         : x86_64
Size         : 192 k
Source       : fftw-3.3.5-11.fc28.src.rpm
Repo         : @System
From repo    : updates
Summary      : A Fast Fourier Transform library
URL          : http://www.fftw.org
License      : GPLv2+
Description  : FFTW is a C subroutine library for computing the Discrete Fourier
             : Transform (DFT) in one or more dimensions, of both real and complex
             : data, and of arbitrary input size.

`

**Comment by koenigjaeger** [comment]
I'll take a look at filing a bug report for Fedora. What version of Julia are you using and have you found that most libraries are updated? I was thinking of building v0.7

-------- Original Message --------

**Comment by rickhg12hs** [comment]
I'm in a "transition period". I've had some projects that are almost completed and I didn't want to change the underlying platform.  I'm currently on an i7 laptop running Fedora 26 and Julia v0.6.4.  I have another, i3 laptop that I might use for traveling development and currently it's running Fedora 27 with the same Julia setup.  Once my projects are completed, I'll update to the latest Fedora and probably install Julia v0.7.0 and v1.0.0 versions (or their most current stable versions in the series).

Note to self:  If you want your version of an OS to go EOL early, and a major breaking version upgrade of your compute language, start a big project with people.  Why should the actual project be the only challenge? :smirk:

**Comment by koenigjaeger** [comment]
Ah I see. I am not sure what your project involves, but Fedora 28 has been very stable for me with a few exceptions with the gnome shell crashing after an update (which are now fixed). I've been wanting to try atomic workstation so I won't have to worry about big version updates with F29 around the corner. Hopefully they'll include Julia v1.0

**Comment by rickhg12hs** [comment]
You can see what's in the pipeline for [Fedora's Julia Package](https://apps.fedoraproject.org/packages/julia/).

**Comment by martinholters** [comment]
Closing as this has never been a problem of DSP.jl itself. Also, on newer Julia, `fft` and friends have moved to FFTW.jl, which should automatically download the required binary dependencies.
