### ISSUE TITLE
conv, conv2, xcorr,  and deconv documentation missing

### ISSUE THREAD

**Issue by galenlynch** [JuliaDSP/DSP.jl#234]
I'm not really sure if this is a DSP.jl issue or one with Julia, but in the transition from 0.6 -> 1.0, the documentation for `conv` and other functions in `dspbase.jl` has seemingly vanished into thin air. At least I have not been able to find documentation for them online.

`conv` and friends used to be in base, and also had documentation on Julia's documentation page. In Julia 0.7/1.0 they was moved into DSP.jl, and their documentation was removed from Julia's documentation. However, they were not added to DSP.jl's. Currently, it is very difficult to figure out what happened to these functions, and I fear that new users may conclude they does not exist. You basically need to try to use `conv` or similar on 0.7 and see the deprecation warning, or randomly try using `DSP.jl` on 1.0 and do `?conv`.

**Comment by ssfrr** [comment]
fixed in #225
