### ISSUE TITLE
convolution docs don't have docs

### ISSUE THREAD

**Issue by ssfrr** [JuliaDSP/DSP.jl#238]
See https://github.com/JuliaDSP/DSP.jl/pull/225#pullrequestreview-167725119 for some more context. Recently the convolution and cross-correlation functions were added to the docs, but it seems that [they're not actually showing up](https://juliadsp.github.io/DSP.jl/latest/convolutions.html).

**Comment by galenlynch** [comment]
The latest build has this warning in the documenter stage of the build:
```
 Warning: the `julia` keyword argument to `Documenter.deploydocs` is removed. Use Travis Build Stages for determining from where to deploy instead. See the section about Hosting in the Documenter manual for more details.
│   caller = ip:0x0
└ @ Core :-1
[ Info: skipping docs deployment.
```
Perhaps the build script needs to be updated?

**Comment by galenlynch** [comment]
@ssfrr Changing the travis configuration and doc build script seems to have fixed the issue.
