### ISSUE TITLE
Why named DSP.jl rather than DigitalSignalProcessing.jl?

### ISSUE THREAD

**Issue by crstnbr** [JuliaDSP/DSP.jl#249]
AFAIU, people are generally encouraged to use verbose names as this makes it easier to find packages.

So I wonder, why has the abbreviation DSP been chosen here?

It seems to break with the convention.

**Comment by ssfrr** [comment]
The DSP package is one of the older Julia packages and pre-dates most discussion of naming conventions. That said, I think DSP is (arguably?) a common-enough acronym that most folks aren't confused. That could be my bias though.

Definitely clarifying in the README is very welcome, thanks!

**Comment by crstnbr** [comment]
Someone made the same point [on discourse](https://discourse.julialang.org/t/where-did-conv-move-to/18399/15) and I tend to agree. I'll update the doc/Readme.md.

**Comment by crstnbr** [comment]
See PR #250.
