### ISSUE TITLE
`xcorr` pads inputs to equal length

### ISSUE THREAD

**Issue by ssfrr** [JuliaDSP/DSP.jl#253]
Naively I'd expect `length(xcorr(X, Y)) == length(X) + length(Y) - 1`, but instead it's `2*max(length(X), length(Y))-1`. This is because it pads its inputs to equal length before handing off to `conv`. I'm not sure why it does this, given that `conv` pads its inputs as part of the FFT algorithm (but then it undoes the effect of the padding before returning the value).

Does anyone know whether this padding is desirable for some reason?

I've been bitten twice by this (once a while ago, and then apparently I forgot about it in the meantime), so at the very least I'd like to document it, but it seems somewhat questionable.

**Comment by ssfrr** [comment]
As further justification why we might want to change this, it's weird that `conv` and `xcorr` will give results with different lengths.

I know this is a breaking change, so we'd need to figure out whether there's a clean way to deprecate it, maybe with a keyword argument that enables the new behavior, and then at some point in the future we can change the default of the kwarg.

**Comment by galenlynch** [comment]
This behaviour is the same as Matlab's `xcorr`, as well as SciPy's `correlate` with default arguments (i.e. `mode = 'full'`). Perhaps adding a keyword to change the `mode` of the result would be nice, but I think the current behaviour is in line with other popular DSP packages.

**Comment by ssfrr** [comment]
In those packages does `conv` do the same thing, or do they likewise have `conv` and `xcorr` behaving differently?

**Comment by galenlynch** [comment]
Matlab - 
No, `conv` is different in both packages.

xcorr: always pads to `2*(max(N,M)) - 1` where `N` is length of the first vector and `M` is length of second vector
conv: padding controlled by `shape` optional paramter, defaults to `full` which is `N + M - 1`

SciPy -
correlate - same default behavior as matlab's xcorr
convolve - same default behavior as matlab's conv

Also, the current behavior returns a symmetric cross correlation, which is nice.

**Comment by galenlynch** [comment]
@ssfrr now that I've been bitten by this a few times as well I agree with you.

**Comment by galenlynch** [comment]
Fixed by #266

**Comment by ssfrr** [comment]
🎉

Thanks @galenlynch!

**Comment by galenlynch** [comment]
My pleasure!
