### ISSUE TITLE
Webpage error

### ISSUE THREAD

**Issue by monsij** [JuliaDSP/DSP.jl#254]
The webpage address provided in the repository description does not works(extra .html). I think it may be changed to `https://juliadsp.github.io/DSP.jl/stable/contents/` or probably `https://juliadsp.github.io/DSP.jl/latest/contents/`

**Screenshot**
![julia](https://user-images.githubusercontent.com/23289387/50134334-72cec380-02b5-11e9-8b36-bc5efab845c8.PNG)

**Comment by monsij** [comment]
Yeah @galenlynch , that is a better way out

**Comment by monsij** [comment]
Any updates @galenlynch ?. Can it be done ?

**Comment by galenlynch** [comment]
Oh I don't have the permissions to change that. I think Alex (@ararslan) might though?

**Comment by monsij** [comment]
Ok not an issue.

**Comment by ararslan** [comment]
I have the power! :zap: It has been removed.
