### ISSUE TITLE
Use overlap-save algorithm for conv?

### ISSUE THREAD

**Issue by galenlynch** [JuliaDSP/DSP.jl#268]
We already use overlap-save for fir filtering, when it is advantageous to do so. It seems like it would make sense to also use overlap-save for `conv`. As fir filtering is just convolution, it's a little weird that we have two totally separate code paths to do the same thing.

**Comment by ssfrr** [comment]
big :+1: for unifying `conv` and `filt`. It's debatable whether we even need separate names for them, but I think that it's nice to be able to easily switch between FIR and IIR filters with `filt`, and it would be weird not to have convolution and only rely on `filt`, so I think it's fine to have both.

**Comment by martinholters** [comment]
Implemented in #286.
