### ISSUE TITLE
Citability

### ISSUE THREAD

**Issue by galenlynch** [JuliaDSP/DSP.jl#311]
As I'm writing up things that use this package, it occurs to me that it would be nice to cite it in some way. Maybe we should think about how to make that possible?

**Comment by curio-sitas** [comment]
Many repositories create a record on [Zenodo](https://zenodo.org/). Zenodo stores archives of the software at different versions (not automatically) and creates a DOI as well as different citation embed code (bibtex...)

**Comment by martinholters** [comment]
I've just enabled Zenodo for this repo, but it will only create an entry once we do the next release.
