### ISSUE TITLE
Distributions.jl failed to be installed due to SpecialFunctions.jl

### ISSUE THREAD

**Issue by VivMendes376** [JuliaDSP/DSP.jl#324]
Apparently, I have a problem related to Distributions.jl. I tried to add Distributions.jl and got this error: (in Windows 10, Atom 1.41.0 x64, Julia1.2). Well, in fact, I had Distributions 0.20 already installed in my computer. I had a problem with QuantEcon which mentioned SpecialFunctions.jl, and I tried to update Distributions.jl. The error comes as:

(v1.2) pkg> add https://github.com/JuliaStats/Distributions.jl
Cloning git-repo https://github.com/JuliaStats/Distributions.jl
Updating git-repo https://github.com/JuliaStats/Distributions.jl
Updating git-repo https://github.com/JuliaStats/Distributions.jl
Resolving package versions...
ERROR: Unsatisfiable requirements detected for package SpecialFunctions [276daf66]:
SpecialFunctions [276daf66] log:
├─possible versions are: [0.7.0-0.7.2, 0.8.0] or uninstalled
├─restricted to versions 0.8.0-0.8 by Distributions [31c24e10], leaving only versions 0.8.0
│ └─Distributions [31c24e10] log:
│ ├─possible versions are: 0.21.7 or uninstalled
│ └─Distributions [31c24e10] is fixed to version 0.21.7
└─restricted to versions 0.7.2 by an explicit requirement — no versions left

**Comment by VivMendes376** [comment]
Funny, when I just use pkg> update Distributions.jl,   it works:

v1.2) pkg> update Distributions.jl
  Updating registry at `C:\Users\Utilizador\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\Utilizador\.julia\environments\v1.2\Project.toml`
 [no changes]
  Updating `C:\Users\Utilizador\.julia\environments\v1.2\Manifest.toml`
 [no changes]

Not sure what is happening here.

**Comment by galenlynch** [comment]
I don't see the relation to DSP.jl?

**Comment by galenlynch** [comment]
This should be fixed by JuliaRegistries/General#5778, and should resolve itself if you update your julia packages. If that doesn't fix it, please reopen this issue.

**Comment by VivMendes376** [comment]
Thanks a lot. It's working. I just updated all packages ("pkg> update") and the problems are gone.

Once again, thanks.

**Comment by galenlynch** [comment]
No problem!
