### ISSUE TITLE
Can not be installed with the latest version of SpecialFunctions

### ISSUE THREAD

**Issue by kagalenko-m-b** [JuliaDSP/DSP.jl#332]
SpecialFunctions library is restricted to versions below 0.8.0
> (v1.3) pkg> add DSP
> Resolving package versions...
> ERROR: Unsatisfiable requirements detected for package SpecialFunctions [276daf66]:
 > SpecialFunctions [276daf66] log:
> ├─possible versions are: [0.7.0-0.7.2, 0.8.0, 0.9.0] or uninstalled
> ├─restricted to versions 0.9.0 by an explicit requirement, leaving only versions 0.9.0
> └─restricted by compatibility requirements with DSP [717857b8] to versions: [0.7.0-0.7.2, 0.8.0] > — no versions left
>  └─DSP [717857b8] log:
>     ├─possible versions are: [0.5.1-0.5.2, 0.6.0-0.6.1] or uninstalled
>     └─restricted to versions * by an explicit requirement, leaving only versions [0.5.1-0.5.2, 0.6.0-0.6.1]

**Comment by ssfrr** [comment]
This is fixed with #330, which has been merged into `master`

**Comment by kagalenko-m-b** [comment]
Thanks.
When will that propagate into centralized Julia repo, from where I install using Pkg.add("DSP")?

**Comment by galenlynch** [comment]
As soon as JuliaRegistries/General#5957 is merged, then the new compatibility should be available.
