### ISSUE TITLE
Blackman window with negative coefficient

### ISSUE THREAD

**Issue by btmit** [JuliaDSP/DSP.jl#347]
I just noticed a small issue with the blackman window: the first and last values are slightly negative.

```
findmin(blackman(257))
(-1.3877787807814457e-17, 1)

findmin(blackman(2048))
(-1.3877787807814457e-17, 1)
```

This is only an issue because other functions that use windows often assume they are non-negative.

I assume this is a numerical issue that can be easily fixed. I haven't run into this problem with other windows, but I haven't checked every single one.

**Comment by JakeZw** [comment]
Many windows go negative in the time domain.  See the paper by Ron Potter at http://papers.vibetech.com/Paper64-CompilationofTimeWindowsandLineShapesRPotter.pdf.  I have attached a figure of the flattop window.

![flapttop](https://user-images.githubusercontent.com/13350908/110704925-a7473680-81c3-11eb-84e5-da9c125e041d.png)
