### ISSUE TITLE
I registered juliadsp.org

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDSP/DSP.jl#354]
I mainly registered it for future use, but just mentioning it here so that folks know. Could perhaps migrate the documentation from github.io to juliadsp.org.

**Comment by galenlynch** [comment]
Thank you! Migrating, or copying, the docs would be a great idea.

**Comment by ViralBShah** [comment]
The easiest thing to do would be to set up the DNS to point to github pages. I can set it up if you can make me an owner temporarily.

**Comment by galenlynch** [comment]
I'm not an owner, but I think @ararslan could do that?

**Comment by ViralBShah** [comment]
You're not an owner of JuliaDSP? Perhaps we should make sure you are. @ararslan Can you give me the owner bit?

**Comment by ararslan** [comment]
I've made Galen an owner and sent Viral an org invite as an owner.

**Comment by galenlynch** [comment]
Thanks!

**Comment by ViralBShah** [comment]
I am migrating docs to the new domain name. Just a heads up - there may be a small period of things giving 404 errors on the webpages.

**Comment by ViralBShah** [comment]
The docs are now at docs.juliadsp.org and working fine. See the updated links in the README.

**Comment by ararslan** [comment]
Thanks, Viral!
