### ISSUE TITLE
Tukey win to rect method error

### ISSUE THREAD

**Issue by 1oly** [JuliaDSP/DSP.jl#364]
Hello,

Calling Tukey window with `alpha=0` redirects to `rect(n,0,0)` which is a method error 
```
tukey(10,0)

MethodError: no method matching rect(::Int64, ::Int64, ::Bool)
Closest candidates are:
  rect(::Integer; padding, zerophase) at /Users/oliver/.julia/packages/DSP/KGj8O/src/windows.jl:139
```
Looks like this line 
https://github.com/JuliaDSP/DSP.jl/blob/d457cc4587a90135475331a56b9f5c1dca380c88/src/windows.jl#L246

should be changed to 

```
rect(n; padding=padding, zerophase=zerophase)
```

Can make the PR (with tests) next week if no one beats me to it.

/Oliver

**Comment by galenlynch** [comment]
Fixed by #365 (thanks!).
