### ISSUE TITLE
Add support of non-0 Nyquist to fftfreq?

### ISSUE THREAD

**Issue by N5N3** [JuliaDSP/DSP.jl#370]
Now fftfreq only return the frequency axis on the 0th Nyquist Band by default.
Maybe we could add a argument, i.e. `fc`, to determine where the axis is.

**Comment by galenlynch** [comment]
That's a good idea, but this function was [moved](https://github.com/JuliaMath/AbstractFFTs.jl/pull/26) to [AbstractFFTs.jl](https://juliamath.github.io/AbstractFFTs.jl/stable/api/#AbstractFFTs.fftfreq). As such, could you please repost this issue in AbstractFFTs.jl? I will close it here in DSP.jl.
