### ISSUE TITLE
freqz for impulse responses

### ISSUE THREAD

**Issue by baggepinnen** [JuliaDSP/DSP.jl#398]
I am missing a way of obtaining the frequency response for an FIR filter. In matlab, I can simply pass a vector of  impulse-response coefficients `h` like `freqz(h, 1)`. Is the appropriate way to wrap the coefficients in `PolynomialRatio` with `[1]` as the denominator?

**Comment by galenlynch** [comment]
Yes I believe so, assuming you are using a `FIRFilter` stateful filter. If that's the case, then see: https://github.com/JuliaDSP/DSP.jl/issues/185#issuecomment-337810967.

Would be great to have `freqz` support this without the workaround.

**Comment by baggepinnen** [comment]
Ah, thanks for the pointer to the older discussion, I managed to miss that. Feel free to close this issue as a duplicate.

**Comment by galenlynch** [comment]
Dup of #185
