### ISSUE TITLE
Convolution of Discrete Signals

### ISSUE THREAD

**Issue by mahdiarsadeghi** [JuliaDSP/DSP.jl#404]
I am trying to run a basic example of convolution for two discrete signals. Assuming <img src="https://render.githubusercontent.com/render/math?math=x[n]=0.2^n \times u[n]"> and <img src="https://render.githubusercontent.com/render/math?math=h[n]=u[n+2]"> . What would be the value of <img src="https://render.githubusercontent.com/render/math?math=y[n]=x[n] \ast h[n]"> for n=-10:10. Here is how I implement it:

```
using Plots, DSP

x(n) = if n<0 0 else 0.2^n end
h(n) = if n<-2 0 else 1 end

n = -10:10
conv(h.(n),x.(n))
```

It doesn't work. Here is the error: 

> `float` not defined on abstractly-typed arrays; please convert to a more specific type

Any idea how may I fix it?

**Comment by mbaz** [comment]
Works for me on DSP 0.6.10 and Julia 1.5.3.

**Comment by mahdiarsadeghi** [comment]
Cool! Yes, it works for my simple example. But it doesn't work for the following: 

```
x(n) = if n<1 0 else 0.25^(n-1) end
h(n) = if n<-2 0 else 1 end

n = -10:10
conv(h.(n),x.(n))
```

If I change 0.25 to 2 it will work again. Any idea why?

**Comment by mbaz** [comment]
I think that `conv` is not expecting an array with eltype `Real`. This works:

    conv(h.(n),convert.(Float64,x.(n)))

However, the real solution is to write your functions so that they return elements of a concrete type, like:

    x(n) = if n < 1 0.0 else 0.25^(n-1) end

Having said that, I think `conv` could handle abstract-typed inputs more gracefully.

**Comment by mahdiarsadeghi** [comment]
I
