### ISSUE TITLE
Inaccurate Diff for v0.6.10 release (Diff describes commits on master that are not in release-0.6)

### ISSUE THREAD

**Issue by drewrobson** [JuliaDSP/DSP.jl#419]
I went looking for why "Rework filter response functions (#384)" wasn't in the latest release (v0.6.10) even though the Diff claims it is.

I think some commits on master didn't make it to release-0.6 before the release was done. Not sure if this was intentional, but just wanted to mention that the Diff description is ahead of the actual release atm.

Thanks for a very useful package!

**Comment by martinholters** [comment]
Version 0.6.10 was a bugfix release that did not tag master, but a branch for that bugfix specifically. Unfortunately, TagBot doesn't deal with that quite well. I've edited the release notes manually.
