### ISSUE TITLE
No docs build for tags

### ISSUE THREAD

**Issue by martinholters** [JuliaDSP/DSP.jl#434]
The [documentation](https://docs.juliadsp.org/stable/contents/) still has v0.6.3 as latest (stable) version. I believe this is because the [Documentation workflow](https://github.com/JuliaDSP/DSP.jl/actions/workflows/Documentation.yml) is not run for tags (at least I don't see any such runs), although AFAICT, it should:
https://github.com/JuliaDSP/DSP.jl/blob/44b5117cc36be2898f9be665ea47e60dc647d0cd/.github/workflows/Documentation.yml#L3-L7
Anyone have a clue what is wrong?

**Comment by rob-luke** [comment]
I have had trouble with this too and ended up creating [two almost identical workflows](https://github.com/rob-luke/fnirs-apps-sourcedata2bids/tree/main/.github/workflows) that just have different startup conditions at the front. So its not just you 😉 .

**Comment by martinholters** [comment]
Might this be some issue with TagBot creating the tag? I'll try removing and re-adding the v0.7.0 tag to see what happens.

**Comment by martinholters** [comment]
Yes, that did trigger the Documentation build. What do we have to do so that tags created by TagBot run the tag-triggered workflows?

**Comment by rob-luke** [comment]
That reminded me of the comment within the documenter docs about how to set up tagbot. But I think ours matches this 

![image](https://user-images.githubusercontent.com/748691/122620806-3fb05980-d0d7-11eb-9520-19c1cd6cdcf1.png)

**Comment by martinholters** [comment]
Aha, looks like there was no deploy key for Documenter configured and neither was the `DOCUMENTER_KEY` secret, so having it set in the workflows didn't help much... I've tried setting it up correctly now, let's see whether it actually works with the upcoming 0.7.2 tag.

**Comment by martinholters** [comment]
Yes, looks like that did it.

**Comment by rob-luke** [comment]
Thanks @martinholters
