### ISSUE TITLE
Filter coefficients error

### ISSUE THREAD

**Issue by JuhaHeiskala** [JuliaDSP/DSP.jl#436]
Hi,
Is the below behaviour intentional?
Or have I misunderstood something....

<pre><font color="#4E9A06"><b>julia&gt; </b></font>cc=DSP.PolynomialRatio([1.0], [1.0,1.0])
PolynomialRatio{:z, Float64}(Polynomials.LaurentPolynomial(1.0), Polynomials.LaurentPolynomial(1.0*z⁻¹ + 1.0))

<font color="#4E9A06"><b>julia&gt; </b></font>ff=DSP.DF2TFilter(cc)
<font color="#EF2929"><b>ERROR: </b></font>ArgumentError: length of state vector must match filter order
Stacktrace:
 [1] <b>DF2TFilter</b>
<font color="#555753">   @ ~/.julia/packages/DSP/C3OhM/src/Filters/</font><font color="#555753"><u style="text-decoration-style:single">filt.jl:137</u></font><font color="#555753"> [inlined]</font>
 [2] <b>DF2TFilter</b><font color="#555753"> (repeats 2 times)</font>
<font color="#555753">   @ ~/.julia/packages/DSP/C3OhM/src/Filters/</font><font color="#555753"><u style="text-decoration-style:single">filt.jl:154</u></font><font color="#555753"> [inlined]</font>
 [3] top-level scope
<font color="#555753">   @ </font><font color="#555753"><u style="text-decoration-style:single">REPL[10]:1</u></font>
</pre>

This was with Julia 1.6.1 and DSP v0.7.2.
I briefly looked at the code and looked to be that state vector is initialized to the longer coefficient length, but then the error comes from a check that the input coefficients and state vector are all the same length. (lines 136-140 in filt.jl)
```
function DF2TFilter{Ti,Si}(coef::PolynomialRatio{:z}, state::Vector) where {Ti,Si}
        length(state) == length(coef.a)-1 == length(coef.b)-1 ||
            throw(ArgumentError("length of state vector must match filter order"))
        new{Ti,Si}(coef, state)
    end
```
Same error happens if the coefficients are padded with zeros to have same length, but not if coefficients are the same length and have non-zero first and last values.

**Comment by martinholters** [comment]
Fallout of #284, I guess. (But note that before, `PolynomialRatio` with different numerator/denominator order was inconsistently defined, so the result of the filtering may not have been what one expected.)
