### ISSUE TITLE
Documentation CI is failing

### ISSUE THREAD

**Issue by rob-luke** [JuliaDSP/DSP.jl#441]
I have noticed that the documentation CI is failing. For example see https://github.com/JuliaDSP/DSP.jl/pull/412/checks?check_run_id=3177629175

I took a look at the GitHub workflows and they seem correct (and haven't changed since we got it up and working). And I looked up the error and it seems to be related to authentication. I also noticed that I don't think I have access to the settings tab any more (maybe I never did, I might be confused between repos).

Based on this I think maybe the security settings for this repo have been updated and possibly the documenter key is no longer valid? I think only @galenlynch or @martinholters have owner rights, do you know if this key or the security settings have been modified? If so, Im happy to help fix. If not, I will dig further to find the issue cause.

https://github.com/JuliaDSP/DSP.jl/blob/69dc131233360e924138ab3ba1ae0c86325c0e9a/.github/workflows/Documentation.yml#L21

**Comment by martinholters** [comment]
I think it's because it's a PR from a fork and the action then doesn't get access to the `DOCUMENTER_KEY` and the `GITHUB_TOKEN` doesn't have write permission in that case, making the push fail. Not sure we can do anything about it. Or should---allowing anyone to open a PR which then has its (maliciously modified) docs deployed sounds like a bad idea.

**Comment by rob-luke** [comment]
So the docs preview is only generated when its a branch from this repo? Makes sense. 

It does make it harder to review a PR though, its nice to check the docs build correctly in other projects I am in. And, not anyone can use the CI, one of us seems to need to hit the `run` button. But I will close as your explanation makes sense. Thanks for the explanation

**Comment by martinholters** [comment]
Approval to run the actions is only required for first-time contributors. That can be configured though. But an option to run a job with elevated permissions would be welcome because I agree, a working preview would definitely be nice.

**Comment by rob-luke** [comment]
I’ll keep my eyes open around other repos for ideas. Thanks Martin
