### ISSUE TITLE
Windows.gaussian behaves strange

### ISSUE THREAD

**Issue by justinbroce** [JuliaDSP/DSP.jl#460]
I am not sure if I am using it wrong or what, but DSP.jl implementation of gaussian filter, produces coefficients drastically different from what scipy.signal gives.

`scipy.signal.gaussian(10,3)`

`array([0.32465247, 0.50633562, 0.70664828, 0.8824969 , 0.98620712,
       0.98620712, 0.8824969 , 0.70664828, 0.50633562, 0.32465247])`

` Windows.gaussian(10,3)
10-element Vector{Float64}:
 0.9862071167439163
 0.991633277050093
 0.9957224806571746
 0.9984579802595297
 0.9998285469356966
 0.9998285469356966
 0.9984579802595297
 0.9957224806571746
 0.991633277050093
 0.9862071167439163
`
If this is a legit issue, I have a julia implementation that matches that scipy gaussian that we could add.

**Comment by mbaz** [comment]
What is the window equation used by scipy? The equation used by DSP.jl is the same as the one used by Matlab as documented here: https://www.mathworks.com/help/signal/ref/gausswin.html

**Comment by justinbroce** [comment]
Well there must be a typo in the one used by DSP.jl, because the numbers are off compared to this: https://www.mathworks.com/help/signal/ref/sigwin.gausswin.generate.html
also the numbers are the same between matlab and octave, and different from scipy.

DSP produces for gaussian(16,3)
` 0.9862071167439163
 0.9896221268507549
 0.9925586888738226
 0.9950124791926823
 0.9969798784123383
 0.9984579802595297
 0.9994445987368581
 0.9999382735100965
 0.9999382735100965
 0.9994445987368581
 0.9984579802595297
 0.9969798784123383
 0.9950124791926823
 0.9925586888738226
 0.9896221268507549
 0.9862071167439163
`
I don't have Matlab, but I tested them against octave https://octave-online.net/, and the numbers are way off.

scipy version for reference https://github.com/scipy/scipy/blob/v1.8.0/scipy/signal/windows/_windows.py#L1216-L1276

**Comment by justinbroce** [comment]
I checked with my school computer's copy of matlab, and the numbers are off. I will make a pull request shortly, making sure the numbers align with Matlab's gausswin()

**Comment by mbaz** [comment]
I think you're correct. In Matlab, the argument is the "width factor" alpha, but in DSP.jl (and scipy) the argument is the standard deviation (which is, IMO, much more consistent). The relationship between alpha and standard deviation is given in the link to the docs I provided above.

The difference between DSP.jl and scipy is probably the way they calculate the time samples. DSP.jl samples in the range `[-0.5, 0.5]`, while scipy seems to sample in `[(-M+1)/2, (M+1)/2]` where `M` is the number of samples (unless I'm missing something).

**Comment by justinbroce** [comment]
Awesome! I checked and you can call 
```julia
using DSP
gaussian(10,inv(3))
```
for the `scipy.signal.gauss`

I'll also leave this here for comparison between scipy and Matlab/Octave

https://stackoverflow.com/questions/71196448/why-does-scipy-signal-windows-gaussian-produce-different-numbers-than-matlab-and/71198127#71198127
