### ISSUE TITLE
Cannot import function freqresp from DSP.jl

### ISSUE THREAD

**Issue by WJ-Huang** [JuliaDSP/DSP.jl#476]
Hi all,

Recently I met a problem that I cannot import function `freqresp` even after `using DSP`, while I can use other functions, such as `PolynomialRatio`. Does anybody know how this problem come? Thanks!

**Comment by martinholters** [comment]
Works for me:
```julia
julia> Pkg.status()
      Status `/tmp/jl_rt9Iuj/Project.toml`
  [717857b8] DSP v0.7.6

julia> import DSP: freqresp

julia> freqresp
freqresp (generic function with 3 methods)

julia> freqresp(::String) = "yes!"
freqresp (generic function with 4 methods)

julia> freqresp("Does importing work?")
"yes!"
```
What exactly are you doing and what's the failure you are seeing?

**Comment by WJ-Huang** [comment]
This is the code that I have when importing the function. I am trying to generate a filter (using `PolynomialRatio`) and calculate its frequency response.
```
(MyProject) pkg> status
Project MyProjectv0.8.0
Status `C:\Work\MyProject.jl\Project.toml`
  [717857b8] DSP v0.6.10

julia> import DSP: freqresp
WARNING: could not import DSP.freqresp into Main

julia> using DSP

julia> freqresp
ERROR: UndefVarError: freqresp not defined
```

**Comment by WJ-Huang** [comment]
I just realized that `freqresp` is not in `DSP v0.6`. Sorry about the disturbance, and thanks for your help. I will close this issue.
