### ISSUE TITLE
Doc issues on JuliaHub with 0.7.9 - Missing docstring. Check Documenter's build log for details.

### ISSUE THREAD

**Issue by scls19fr** [JuliaDSP/DSP.jl#547]
Hello,

I noticed a lot of doc issues with 0.7.9

See

https://docs.juliahub.com/DSP/OtML7/0.7.9/windows/#DSP.Windows.hamming

we can see

    Missing docstring.
    Missing docstring for hamming. Check Documenter's build log for details.

and compare to

https://docs.juliahub.com/DSP/OtML7/0.7.8/windows/#DSP.Windows.hamming

Kind regards

**Comment by martinholters** [comment]
Oh, that's unfortunate. Looking at https://github.com/JuliaDSP/DSP.jl/compare/v0.7.8...v0.7.9 the only reason for the breakage that presents itself is the change in the CI setup and how it builds the docs, although that should in principle do the same as before. And the logs of the 0.7.9 run have been garbage-collected by now, so I don't know what went wrong there.
The good news is that everything looks fine on master, so the docs for 0.8.0 should hopefully be ok again.

**Comment by martinholters** [comment]
Ah, I had missed that those are JuliaHub links. So my comment above is moot.

**Comment by scls19fr** [comment]
Oh yes https://docs.juliadsp.org/stable/filters/ looks corrects

**Comment by ViralBShah** [comment]
Closing since this is a JuliaHub issue.
