### ISSUE TITLE
Docstring error - f parameter

### ISSUE THREAD

**Issue by s-celles** [JuliaDSP/DSP.jl#549]
Hello,

I think there is an error with this docstring

https://github.com/JuliaDSP/DSP.jl/blob/3e3524f6ac7a52ab2f06843328f0b3b41bd62bb8/src/Filters/filt.jl#L122-L131

what is `f` parameter (is it `coeff` ?) ?

Kind regards

**Comment by mbaz** [comment]
Yes, I think it should be `coef` instead of `f`. Probably a copy/paste error, since `filt` takes an argument `f`.
