### ISSUE TITLE
Maybe filter example need to be updated?

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaDSP/DSP.jl#567]
When I run 2nd example from https://docs.juliadsp.org/latest/filters/#Examples:

I get the following error:
```julia
x = rand(10000);
responsetype = Bandpass(10, 40)
# ERROR: frequencies must be less than the Nyquist frequency 1.0
designmethod = Butterworth(4)
filt(digitalfilter(responsetype, designmethod; fs=1000), x)
```

I guess, I must be using this:

```julia
responsetype = Bandpass(10, 40, fs = 1000)
designmethod = Butterworth(4)
filt(digitalfilter(responsetype, designmethod), x)
```

Is this correct? If yes, does it help to make a PR for the documentation?

**Comment by martinholters** [comment]
Check https://docs.juliadsp.org/stable/filters/#Examples. The code you are citing is from the documentation for the current `dev` version, while you seem to be running a regular release version.
The same thing happened in #560, so it seems the `dev` docs might be linked to too prominently from somewhere. How did you get there?
Anyway, the docs are correct if one uses corresponding versions, so closing.

**Comment by Alexander-Barth** [comment]
Thank you for the info.
 I clicked indeed on the wrong documentation link.
