### ISSUE TITLE
periodogram normalization

### ISSUE THREAD

**Issue by andferrari** [JuliaDSP/DSP.jl#98]
the normalization "so that the area under the periodogram is equal to the uncentered variance of the original signal" is rather unusual. 
Possibility to have also the classical normalisation (f_e/N)*abs(FFT)^2 would be great !

**Comment by simonster** [comment]
What is `f_e` supposed to be there?

I believe our current normalization is correct, at least if you're trying to use the periodogram to estimate the power spectral density. The rationale is described in [this vignette](http://cran.r-project.org/web/packages/psd/vignettes/normalization.pdf) for the R `psd` function. See also some discussion of normalization in DSP.jl#42.

**Comment by andferrari** [comment]
Thank you for the answer. 

Your normalization is correct. 
I was confused by "uncentered variance of the original signal"  in the [Doc](http://dspjl.readthedocs.org/en/latest/periodograms.html). I would say
something like "(average) power of the original signal"

**Comment by simonster** [comment]
Most of the references I've seen define the power spectral density as a measure of how the variance is distributed (e.g. [Wikipedia](http://en.wikipedia.org/wiki/Spectral_density)). But if you have an alternative reference we could extend the description.

**Comment by andferrari** [comment]
To clarify. You normalize the periodogram such that its area equals P(x) = (1/N) \sum_{n=1}^N x_n^2
I totally agree with this, but P(x) is not the variance of x_n.  P(x) is the average power of x_n (or eventually its second order moment). The variance of x is P(x-mean(x)).

**Comment by simonster** [comment]
Well, the uncentered variance is the variance without mean subtraction, which is your formula above. But I have no qualms with using both terms in the docs.
